### ISSUE TITLE
Handle permission error

### ISSUE THREAD

**Issue by jordanegiuly** [CoorpAcademy/trellit#115]

**Comment by CoorpAcademyAdmin** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;xEUYkTm4&#x2F;587-handle-permission-error"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Handle permission error</a>
