### ISSUE TITLE
Cloture d'un ticket en backlog

### ISSUE THREAD

**Issue by matthieuharbonnier** [CoorpAcademy/trellit#132]
Lorsqu'un ticket est fermé dans GitHub dont la card est dans le board "backlog", cette dernière ne présente pas de modification.

**To do's** : 
- Archiver la card présente dans n'importe quelle liste du board "backlog" lorsque le ticket GitHub est clôturé
- Par ailleurs, fermer un ticket GitHub lorsque la card lui étant associée est archivée

**Comment by jordanegiuly** [comment]
ok
