### ISSUE TITLE
Assignation GitHub > plus d'assignation Trello

### ISSUE THREAD

**Issue by matthieuharbonnier** [CoorpAcademy/trellit#146]
Lorsqu'un utilisateur s'assigne dans Github à un ticket, ce dernier est bougé de colonne dans Trello mais l'utilisateur n'est pas affecté à la Carte.

Ex 1
https://github.com/CoorpAcademy/coorpacademy/issues/6242
Assignation Joan le 19.11 vers 12h20
![_0_5___6242_-_sqypark__changement_de_wording_sur_la_page_de_connexion_de_current_sprint___trello](https://cloud.githubusercontent.com/assets/14977676/11269671/ab0db23e-8eb8-11e5-8fcb-7f8e89b06aa2.png)

Ex 2
https://github.com/CoorpAcademy/coorpacademy/issues/6210

Ex 3
https://github.com/CoorpAcademy/coorpacademy/issues/6240

**Comment by jordanegiuly** [comment]
ok
