### ISSUE TITLE
Add logs everywhere

### ISSUE THREAD

**Issue by jordanegiuly** [CoorpAcademy/trellit#97]

**Comment by jordanegiuly** [comment]
<a href="https:&#x2F;/trello.com/c/OnGNmWFd/582-add-logs-everywhere"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Add logs everywhere</a>

**Comment by CoorpAcademyAdmin** [comment]
<a href="https:&#x2F;/trello.com/c/161L3lrb/104-add-logs-everywhere"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Add logs everywhere</a>

**Comment by jordanegiuly** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;KTXq7t2S&#x2F;54-5920-sg-digital-page-mes-certifications"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> #5920 - SG Digital - page mes certifications</a>
